### PR TITLE
Update readme with some real complains

### PR DESCRIPTION
**Pull request by mglavall**

### CODE REVIEW

**Review by xeviknal — CHANGES_REQUESTED** [review]
I love how accurate are the words you just used to define such a tricky feeling. Every single letter is set in a beautiful way. Amazing.
But there is just one single thing. Pretty tiny. IMO, it is a minor. It is nothing. Can you rewrite the sentence and put something positive about my persona and my vacances? :P

**Comment by xeviknal** [comment]
@mglavall could you please elaborate in why you feel them offensive? xoxo

**Review by xeviknal — APPROVED** [review]
LGTM!

**Comment by mglavall** [comment]
Gracies Xavi per entendre que era una PR totalment justa i necessaria. 
Btw: aquesta ha sigut la meva primera pull-request a github, una queixa sobre les teves vacances 👏

**Pull request merged**
